#!/usr/bin/env sh

# Load config to setup required env variables
export VSCODE_NVIM=true
export NVIM_APPNAME='vscode-nvim'

# if [ -f "$HOME/user-scripts/bin/detection" ]; then
#   \. "$HOME/user-scripts/bin/detection"
# elif [ -f "$HOME/.usr_conf/load_conf.sh" ]; then
#   \. "$HOME/.usr_conf/load_conf.sh"
# fi
script_path="$(readlink -f "$0")"
script_dir="$(dirname "$script_path")"
\. "$script_dir/detection"

# Add nix to environment
if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]; then
  \. "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi # added by Nix installer

# Add home manager if available
if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
  \. "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
fi

# Launch nvim
exec nvim "$@"

